apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      mylabelname: game
  replicas: 1
  template: #template for pods
    metadata:
      labels: 
        mylabelname: game
    spec:
      containers:
      - name: game
        image: emailtovamos/game-repo